version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        uid: ${UID}
        gid: ${GID}
    container_name: php_${PROJECT_NAME}
    env_file:
      - ./.env
    volumes:
      - .:/var/www:delegated

  web:
    depends_on:
      - php
