version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
      args:
        uid: ${UID}
        gid: ${GID}
    container_name: php_${PROJECT_NAME}
    env_file:
      - ./.env
    volumes:
      - .:/var/www:delegated
    extra_hosts:
      - host.docker.internal:${DOCKER_BRIDGE_GATEWAY_IP}

  web:
    depends_on:
      - php
