version: "3.7"

services:
  chrome:
    image: drupalci/webdriver-chromedriver:production
    container_name: chrome_${PROJECT_NAME}
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_ADMIN
    volumes:
      - /dev/shm:/dev/shm
    entrypoint:
      - chromedriver
      - "--no-sandbox"
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="
      - "--allowed-origins=*"
