version: "3.7"

services:
  web:
    image: nginx:1.25.3-alpine
    container_name: web_${PROJECT_NAME}
    env_file:
      - .env
    volumes:
      - .:/var/www:delegated
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./conf/nginx/default.conf:/etc/nginx/templates/default.conf.template:delegated
    working_dir: /var/www
    ports:
      - "8081:80"
